version: '3.8'

services:
  # Main API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder  # Use builder stage for development
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"  # Main API port
      - "9229:9229"  # Debug port
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      STORAGE_EMULATOR_HOST: http://gcp-emulator:8085
      PUBSUB_EMULATOR_HOST: gcp-emulator:8086
      GOOGLE_CLOUD_PROJECT: pharma-pipeline-dev
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /run
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    depends_on:
      redis:
        condition: service_healthy
      gcp-emulator:
        condition: service_started
    networks:
      - pharma_pipeline_network

  # Redis cache service
  redis:
    image: redis:6.2-alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data:delegated
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 128M
    networks:
      - pharma_pipeline_network

  # GCP service emulators
  gcp-emulator:
    image: google/cloud-sdk:latest
    ports:
      - "8085:8085"  # Storage emulator
      - "8086:8086"  # Pub/Sub emulator
    environment:
      STORAGE_EMULATOR_HOST: http://localhost:8085
      PUBSUB_EMULATOR_HOST: localhost:8086
      GOOGLE_CLOUD_PROJECT: pharma-pipeline-dev
    command: >
      sh -c "
        gcloud config set project pharma-pipeline-dev &&
        gcloud beta emulators storage start --host-port=0.0.0.0:8085 & 
        gcloud beta emulators pubsub start --host-port=0.0.0.0:8086
      "
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M
    networks:
      - pharma_pipeline_network

volumes:
  redis_data:
    driver: local
  node_modules:
    driver: local

networks:
  pharma_pipeline_network:
    driver: bridge
    internal: true
    enable_ipv6: false
    driver_opts:
      com.docker.network.bridge.name: pharma-pipeline
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16